---
title: "Quiz 3"
author: "Ivy Fernandes"
date: "5/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction to dplyr
```{r}
#install.packages("dplyr")
#library(dplyr)
dat<-read.csv("femaleMiceWeights.csv")
View(dat)

#using the commands select (select columns and variables in the dataset) and filter (filter certain units)

controls<-filter(dat,Diet=="chow")
View(controls)

bwcontrol<-select(controls, Bodyweight)

#convert the bodyweight into vector so that we can utilize it later

vec<-unlist(bwcontrol)

# typing everything on one line using '%>%'
controls<-filter(dat,Diet=="chow") %>% select(Bodyweight) %>% unlist
```

## Exercises
```{r}
install.packages("downloader")
library(downloader)
url="https://raw.githubusercontent.com/genomicsclass/dagdata/master/inst/extdata/msleep_ggplot2.csv"
filename <- basename(url)
download(url,filename)
```

## Exercise 1
```{r}
# Read in the msleep_ggplot2.csv file with the function read.csv() and use the function class() to determine what type of object is returned.
data<-read.csv("msleep_ggplot2.csv")
class(data)
```

## Exercise 2
```{r}
# Now use the filter() function to select only the primates. How many animals in the table are primates? Hint: the nrow() function gives you the number of rows of a data frame or matrix.
View(data) #primates is part of the 'order' set
primates<-filter(data, order=="Primates")
View(primates)
nrow(primates)

```

## Exercise 3
```{r}
#What is the class of the object you obtain after subsetting the table to only include primates?
class(primates)
```



## Exercise 4
```{r}
# Now use the select() function to extract the sleep (total) for the primates. What class is this object? Hint: use %>% to pipe the results of the filter() function to select().

sleep<-filter(data, order=="Primates") %>% select(sleep_total)
class(sleep)
```

## Exercise 5
```{r}
# Now we want to calculate the average amount of sleep for primates (the average of the numbers computed above). One challenge is that the mean() function requires a vector so, if we simply apply it to the output above, we get an error. Look at the help file for unlist() and use it to compute the desired average. What is the average amount of sleep for primates?
sleepmean<-filter(data, order=="Primates") %>% select(sleep_total) %>% unlist %>% mean
sleepmean
```

## Exercise 6
```{r}
# For the last exercise, we could also use the dplyr summarize() function. We have not introduced this function, but you can read the help file and repeat exercise 5, this time using just filter() and summarize() to get the answer. What is the average amount of sleep for primates calculated by summarize()

sleep2<-filter(data, order=="Primates")%>%
summarise(mean=mean(sleep_total))
sleep2

```

